"""
Tamara Alhajj
Project Euler Q12
The sequence of triangle numbers is generated by adding the natural numbers.
Note: triangle numbers are given by C(n+1, 2)
What is the value of the first triangle number to have over five hundred divisors?
"""
